cShareSystems.load_pas("Pwn4two", [
        "coui://ui/mods/pwn4two/systems/kappa_shared.pas",
	"coui://ui/mods/pwn4two/systems/1v1_or_shared.pas",
	"coui://ui/mods/pwn4two/systems/molten.pas",
	"coui://ui/mods/pwn4two/systems/frontlines.pas",
        "coui://ui/mods/pwn4two/systems/control.pas",
        "coui://ui/mods/pwn4two/systems/farenheit.pas",
        "coui://ui/mods/pwn4two/systems/crackdown.pas",
	"coui://ui/mods/pwn4two/systems/powercoms.pas",
        "coui://ui/mods/pwn4two/systems/mania.pas",
        "coui://ui/mods/pwn4two/systems/attack_on titan.pas",
        "coui://ui/mods/pwn4two/systems/calico.pas",	
	"coui://ui/mods/pwn4two/systems/4v4.pas",	
        "coui://ui/mods/pwn4two/systems/chronos.pas",
	"coui://ui/mods/pwn4two/systems/mirrored_place.pas",
	"coui://ui/mods/pwn4two/systems/return_home.pas",
	"coui://ui/mods/pwn4two/systems/incontrovertible.pas",	
	"coui://ui/mods/pwn4two/systems/5v5_shared.pas",
	"coui://ui/mods/pwn4two/systems/dodecahedron.pas",
        "coui://ui/mods/pwn4two/systems/all_out war.pas"
]);
