cShareSystems.load_pas("Pwn4two", [
	"coui://ui/mods/pwn4two/systems/ice_combat.pas",
	"coui://ui/mods/pwn4two/systems/lava_fight.pas",
        "coui://ui/mods/pwn4two/systems/kappa_shared.pas",
	"coui://ui/mods/pwn4two/systems/1v1_or_shared.pas",
	"coui://ui/mods/pwn4two/systems/molten.pas",
	"coui://ui/mods/pwn4two/systems/frontlines.pas",
	"coui://ui/mods/pwn4two/systems/frozen.pas",
	"coui://ui/mods/pwn4two/systems/lockery.pas",
	"coui://ui/mods/pwn4two/systems/forest_temple.pas",
        "coui://ui/mods/pwn4two/systems/control.pas",
	"coui://ui/mods/pwn4two/systems/trials.pas",
	"coui://ui/mods/pwn4two/systems/chlorophyte.pas",
        "coui://ui/mods/pwn4two/systems/farenheit.pas",
        "coui://ui/mods/pwn4two/systems/crackdown.pas",
	"coui://ui/mods/pwn4two/systems/powercoms.pas",
        "coui://ui/mods/pwn4two/systems/mania.pas",
        "coui://ui/mods/pwn4two/systems/attack_on titan.pas",
        "coui://ui/mods/pwn4two/systems/calico.pas",
	"coui://ui/mods/pwn4two/systems/we_rek dem mandem.pas",
	"coui://ui/mods/pwn4two/systems/4v4.pas",	
        "coui://ui/mods/pwn4two/systems/chronos.pas",
	"coui://ui/mods/pwn4two/systems/mirrored_place.pas",
	"coui://ui/mods/pwn4two/systems/hold_me.pas",
	"coui://ui/mods/pwn4two/systems/return_home.pas",
	"coui://ui/mods/pwn4two/systems/incontrovertible.pas",	
	"coui://ui/mods/pwn4two/systems/5v5_shared.pas",
	"coui://ui/mods/pwn4two/systems/dodecahedron.pas",
	"coui://ui/mods/pwn4two/systems/wadiya_2018.pas",
        "coui://ui/mods/pwn4two/systems/all_out war.pas",
	"coui://ui/mods/pwn4two/systems/war_of the worlds.pas",
	"coui://ui/mods/pwn4two/systems/6_x 3.pas",
	"coui://ui/mods/pwn4two/systems/stolen_sixmetry ns.pas",
	"coui://ui/mods/pwn4two/systems/duel_planets.pas",
	"coui://ui/mods/pwn4two/systems/the_big squeeze.pas",
	"coui://ui/mods/pwn4two/systems/32_friends.pas",
	"coui://ui/mods/pwn4two/systems/dualdecahedron.pas",
	"coui://ui/mods/pwn4two/systems/dog_eat dog.pas"

]);
